# Generated by Django 4.0.4 on 2022-05-31 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(help_text='A movie title', max_length=120, unique=True)),
                ('Year', models.IntegerField(default=1, help_text='year of movie')),
                ('Rated', models.CharField(default='N.A', help_text='movies rating', max_length=120)),
                ('Released', models.CharField(default='N.A', help_text='movie released time', max_length=120)),
                ('Runtime', models.CharField(default='N.A', help_text='total runtime', max_length=120)),
                ('Genre', models.CharField(default='N.A', help_text='genres', max_length=120)),
                ('Director', models.CharField(blank=True, help_text='directors', max_length=120, null=True)),
                ('Writer', models.CharField(default='N.A', help_text='writters', max_length=120)),
                ('Actors', models.CharField(default='N.A', help_text='Actors', max_length=120)),
                ('Plot', models.CharField(default='N.A', help_text='plot', max_length=120)),
                ('Language', models.CharField(blank=True, help_text='language', max_length=120, null=True)),
                ('Country', models.CharField(default='N.A', help_text='movie country', max_length=120)),
                ('Awards', models.CharField(blank=True, help_text='movie awards', max_length=120, null=True)),
                ('Poster', models.URLField(default='N.A', help_text='movies poster image url', max_length=300)),
                ('Ratings', models.CharField(default='N.A', help_text='A movie title', max_length=120)),
                ('Metascore', models.IntegerField(default='N.A', help_text='Meta score')),
                ('imdbRating', models.FloatField(default='N.A', help_text='imbd rating')),
                ('imdbVotes', models.CharField(default='N.A', help_text='movies imbd votes', max_length=20)),
                ('imdbID', models.CharField(default='N.A', help_text='movies imbs id', max_length=10)),
                ('Type', models.CharField(default='N.A', help_text='movie type', max_length=20)),
                ('DVD', models.CharField(blank=True, help_text='Dvd release date', max_length=20, null=True)),
                ('BoxOffice', models.CharField(default='N.A', help_text='A box office profit', max_length=120)),
                ('Production', models.CharField(default='N.A', help_text='some production data', max_length=120)),
                ('Website', models.URLField(default='N.A', help_text='movies website url')),
                ('Response', models.BooleanField(default='N.A', help_text='Response')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=230)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
