# Generated by Django 4.0.4 on 2022-06-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_movie_boxoffice_alter_movie_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.IntegerField(help_text='Meta score', null=True),
        ),
    ]
