# Generated by Django 4.0.4 on 2022-06-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_metascore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.CharField(default='N.A', help_text='Meta score', max_length=255),
        ),
    ]
